### ISSUE TITLE
annotation 3d label?

### ISSUE THREAD

**Issue by jeannotes** [Manchery/ImageLabeler#1]
hi , is this 3d cuboid annotation tool?

**Comment by Manchery** [comment]
Sorry for response after a long time. Yeah, it can annotate cuboid, but only on a stack of 2D images, just like these [example images](https://github.com/Manchery/ImageLabeler/tree/master/example_images/images3d).
This project is a homework for me as a student, so codes and documents are crude. Sorry for the crudeness!
