### ISSUE TITLE
How to use segmentation feature on 2d images

### ISSUE THREAD

**Issue by mfran89** [Manchery/ImageLabeler#2]
Good afternoon,

I am fairly new to using this annotation tool (i have used the labelme from (https://github.com/wkentaro/labelme)), and might have missed a step but I am trying to use the segmentation feature to annotate some objects on a 2d image. For example when I use the segmentation with circular pen, and i have defined a label , i click the label and use the pen on the image. However the color of pen shows as white (as if invisible) and its not using the label color like i intended to use it. 

Could you explain how to use the segmentation feature and the any of the tools within it? I think i might have missed something. Appreciate any help on this, and awesome job on making the program. 

Sincerely
Mike
<img width="1904" alt="Screen Shot 2022-03-11 at 3 00 46 PM" src="https://user-images.githubusercontent.com/10718810/157950512-a5ea6230-d884-4e86-97d1-221d5ad881df.png">

**Comment by mfran89** [comment]
Never mind I was able to decode the pdf you recommended in to english (https://cloud.tsinghua.edu.cn/d/55f9b7ae115e488fae5c/) . 
So the steps are

1. Select the tool (like circle pen)
2. Create a label
3. Brush the area you want with the white brush
4. Click "Enter" on the keyboard, the color of the paint will change to the label, and that will create one annotated object, and you can see it in the annotated list.

Again thank you very much for the tool !
Mike

**Comment by Manchery** [comment]
Hi, Mike. It's a pleasure to help you and thank you very much for your patience to translate the documentation in Chinese !
