### ISSUE TITLE
如果要以XML格式读写标注框数据,有什么思路不

### ISSUE THREAD

**Issue by ChinaRush** [Manchery/ImageLabeler#4]

**Comment by Manchery** [comment]
手写或者调用一个格式转换函数即可

**Comment by ChinaRush** [comment]
查了一些资料，很多手写的格式转化函数qt都不支持， 而我想利用qt 的QXml 读写流，直接生成标准的VOC数据集格式的XML， 我是C++ 新手，
`RectAnnotationItem * item;
  AnnotationContainer *items;`
items 并不是item类的容器把。现在要把所有的RectAnnotation（标签类别，矩形框，图片信息） 写入，利用现有的数据能完成吗？或者是不是要重新设计一个RectAnnotation的容器。谢谢大佬

**Comment by Manchery** [comment]
首先，这是我的课程作业，所以我设计的并不会非常具有扩展性。
另一方面，我觉得你的需求不难实现。我的应用已经定义了一种输入输出格式，你甚至不需要在源码里进行修改，只要在输入输出文件上做预处理和后处理即可。如果一定要修改源码，找到我输入和输出json格式的函数，对照着改成输入输出xml即可

**Comment by ChinaRush** [comment]
明白，非常感谢
