### ISSUE TITLE
编译遇到的问题

### ISSUE THREAD

**Issue by DirtyBoy-53** [Manchery/ImageLabeler#5]
你好请问这个仓库的代码编译是能正常通过的吗，我克隆到本地后遇到大量的错误警告，Qt版本是5.14的。
![Snipaste_2023-12-08_15-53-18](https://github.com/Manchery/ImageLabeler/assets/54431298/7b0bce94-58e7-4746-b9c0-a7ee57f252b4)

**Comment by Manchery** [comment]
您好，这个项目比较久远了，我记不太清了，但根据文档，https://github.com/Manchery/ImageLabeler/blob/master/doc/%E5%9F%BA%E4%BA%8EQt%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%9B%BE%E7%89%87%E6%95%B0%E6%8D%AE%E6%A0%87%E6%B3%A8%E5%B7%A5%E5%85%B7_%E6%96%87%E6%A1%A3.pdf
应该是能在 Qt 5.12.4 下编译的

**Comment by DirtyBoy-53** [comment]
是的，确实能编译，是我使用MSVC编译器才出现的报错，感谢您的回复。



---原始邮件---
发件人: "Jialong ***@***.***&gt;
发送时间: 2023年12月9日(周六) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Manchery/ImageLabeler] 编译遇到的问题 (Issue #5)




 
您好，这个项目比较久远了，我记不太清了，但根据文档，https://github.com/Manchery/ImageLabeler/blob/master/doc/%E5%9F%BA%E4%BA%8EQt%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%9B%BE%E7%89%87%E6%95%B0%E6%8D%AE%E6%A0%87%E6%B3%A8%E5%B7%A5%E5%85%B7_%E6%96%87%E6%A1%A3.pdf
 应该是能在 Qt 5.12.4 下编译的

**Comment by CugAgo** [comment]
> 是的，确实能编译，是我使用MSVC编译器才出现的报错，感谢您的回复。
> […](#)
> ---原始邮件--- 发件人: "Jialong ***@***.***&gt; 发送时间: 2023年12月9日(周六) 晚上9:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Manchery/ImageLabeler] 编译遇到的问题 (Issue #5) 您好，这个项目比较久远了，我记不太清了，但根据文档，https://github.com/Manchery/ImageLabeler/blob/master/doc/%E5%9F%BA%E4%BA%8EQt%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%9B%BE%E7%89%87%E6%95%B0%E6%8D%AE%E6%A0%87%E6%B3%A8%E5%B7%A5%E5%85%B7_%E6%96%87%E6%A1%A3.pdf 应该是能在 Qt 5.12.4 下编译的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，可以问一下您是使用哪个版本的QT以及编译器编译的吗，是5.14和mingw64吗

**Comment by DirtyBoy-53** [comment]
当时我应该是使用5.15.2的msvc2019编译的，没办法编过，但是换到mingwin64就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月5日(周四) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Manchery/ImageLabeler] 编译遇到的问题 (Issue #5)




  
是的，确实能编译，是我使用MSVC编译器才出现的报错，感谢您的回复。
 …
 ---原始邮件--- 发件人: "Jialong @.&gt; 发送时间: 2023年12月9日(周六) 晚上9:27 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Manchery/ImageLabeler] 编译遇到的问题 (Issue #5) 您好，这个项目比较久远了，我记不太清了，但根据文档，https://github.com/Manchery/ImageLabeler/blob/master/doc/%E5%9F%BA%E4%BA%8EQt%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%9B%BE%E7%89%87%E6%95%B0%E6%8D%AE%E6%A0%87%E6%B3%A8%E5%B7%A5%E5%85%B7_%E6%96%87%E6%A1%A3.pdf 应该是能在 Qt 5.12.4 下编译的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
您好，可以问一下您是使用哪个版本的QT以及编译器编译的吗，是5.14和mingw64吗
